/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IClientesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Aderir ao produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente faça adesão ao produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AdesaoResponse</returns>
        AdesaoResponse AderirProduto(AdesaoRequest adesaoRequest, int operationIndex = 0);

        /// <summary>
        /// Aderir ao produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente faça adesão ao produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AdesaoResponse</returns>
        ApiResponse<AdesaoResponse> AderirProdutoWithHttpInfo(AdesaoRequest adesaoRequest, int operationIndex = 0);
        /// <summary>
        /// Alterar valor mensal
        /// </summary>
        /// <remarks>
        /// Altera o valor mensal de aporte do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AlterarValorMensalResponse</returns>
        AlterarValorMensalResponse AlterarValorMensal(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0);

        /// <summary>
        /// Alterar valor mensal
        /// </summary>
        /// <remarks>
        /// Altera o valor mensal de aporte do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AlterarValorMensalResponse</returns>
        ApiResponse<AlterarValorMensalResponse> AlterarValorMensalWithHttpInfo(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0);
        /// <summary>
        /// Consultar carteira (custódia)
        /// </summary>
        /// <remarks>
        /// Retorna a carteira de ativos do cliente em custódia
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CarteiraResponse</returns>
        CarteiraResponse ConsultarCarteira(long clienteId, int operationIndex = 0);

        /// <summary>
        /// Consultar carteira (custódia)
        /// </summary>
        /// <remarks>
        /// Retorna a carteira de ativos do cliente em custódia
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CarteiraResponse</returns>
        ApiResponse<CarteiraResponse> ConsultarCarteiraWithHttpInfo(long clienteId, int operationIndex = 0);
        /// <summary>
        /// Consultar rentabilidade detalhada
        /// </summary>
        /// <remarks>
        /// Retorna a rentabilidade detalhada do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RentabilidadeResponse</returns>
        RentabilidadeResponse ConsultarRentabilidade(long clienteId, int operationIndex = 0);

        /// <summary>
        /// Consultar rentabilidade detalhada
        /// </summary>
        /// <remarks>
        /// Retorna a rentabilidade detalhada do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RentabilidadeResponse</returns>
        ApiResponse<RentabilidadeResponse> ConsultarRentabilidadeWithHttpInfo(long clienteId, int operationIndex = 0);
        /// <summary>
        /// Sair do produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente saia do produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SaidaResponse</returns>
        SaidaResponse SairProduto(long clienteId, int operationIndex = 0);

        /// <summary>
        /// Sair do produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente saia do produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SaidaResponse</returns>
        ApiResponse<SaidaResponse> SairProdutoWithHttpInfo(long clienteId, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IClientesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Aderir ao produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente faça adesão ao produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AdesaoResponse</returns>
        System.Threading.Tasks.Task<AdesaoResponse> AderirProdutoAsync(AdesaoRequest adesaoRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Aderir ao produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente faça adesão ao produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AdesaoResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AdesaoResponse>> AderirProdutoWithHttpInfoAsync(AdesaoRequest adesaoRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Alterar valor mensal
        /// </summary>
        /// <remarks>
        /// Altera o valor mensal de aporte do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AlterarValorMensalResponse</returns>
        System.Threading.Tasks.Task<AlterarValorMensalResponse> AlterarValorMensalAsync(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Alterar valor mensal
        /// </summary>
        /// <remarks>
        /// Altera o valor mensal de aporte do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AlterarValorMensalResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AlterarValorMensalResponse>> AlterarValorMensalWithHttpInfoAsync(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Consultar carteira (custódia)
        /// </summary>
        /// <remarks>
        /// Retorna a carteira de ativos do cliente em custódia
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CarteiraResponse</returns>
        System.Threading.Tasks.Task<CarteiraResponse> ConsultarCarteiraAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Consultar carteira (custódia)
        /// </summary>
        /// <remarks>
        /// Retorna a carteira de ativos do cliente em custódia
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CarteiraResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CarteiraResponse>> ConsultarCarteiraWithHttpInfoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Consultar rentabilidade detalhada
        /// </summary>
        /// <remarks>
        /// Retorna a rentabilidade detalhada do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RentabilidadeResponse</returns>
        System.Threading.Tasks.Task<RentabilidadeResponse> ConsultarRentabilidadeAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Consultar rentabilidade detalhada
        /// </summary>
        /// <remarks>
        /// Retorna a rentabilidade detalhada do cliente
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RentabilidadeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RentabilidadeResponse>> ConsultarRentabilidadeWithHttpInfoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Sair do produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente saia do produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SaidaResponse</returns>
        System.Threading.Tasks.Task<SaidaResponse> SairProdutoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Sair do produto
        /// </summary>
        /// <remarks>
        /// Permite que um cliente saia do produto de compra programada
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SaidaResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SaidaResponse>> SairProdutoWithHttpInfoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IClientesApi : IClientesApiSync, IClientesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ClientesApi : IClientesApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ClientesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ClientesApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ClientesApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ClientesApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Aderir ao produto Permite que um cliente faça adesão ao produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AdesaoResponse</returns>
        public AdesaoResponse AderirProduto(AdesaoRequest adesaoRequest, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<AdesaoResponse> localVarResponse = AderirProdutoWithHttpInfo(adesaoRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Aderir ao produto Permite que um cliente faça adesão ao produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AdesaoResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<AdesaoResponse> AderirProdutoWithHttpInfo(AdesaoRequest adesaoRequest, int operationIndex = 0)
        {
            // verify the required parameter 'adesaoRequest' is set
            if (adesaoRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'adesaoRequest' when calling ClientesApi->AderirProduto");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = adesaoRequest;

            localVarRequestOptions.Operation = "ClientesApi.AderirProduto";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<AdesaoResponse>("/api/clientes/adesao", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AderirProduto", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Aderir ao produto Permite que um cliente faça adesão ao produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AdesaoResponse</returns>
        public async System.Threading.Tasks.Task<AdesaoResponse> AderirProdutoAsync(AdesaoRequest adesaoRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<AdesaoResponse> localVarResponse = await AderirProdutoWithHttpInfoAsync(adesaoRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Aderir ao produto Permite que um cliente faça adesão ao produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="adesaoRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AdesaoResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<AdesaoResponse>> AderirProdutoWithHttpInfoAsync(AdesaoRequest adesaoRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'adesaoRequest' is set
            if (adesaoRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'adesaoRequest' when calling ClientesApi->AderirProduto");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = adesaoRequest;

            localVarRequestOptions.Operation = "ClientesApi.AderirProduto";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AdesaoResponse>("/api/clientes/adesao", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AderirProduto", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Alterar valor mensal Altera o valor mensal de aporte do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AlterarValorMensalResponse</returns>
        public AlterarValorMensalResponse AlterarValorMensal(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<AlterarValorMensalResponse> localVarResponse = AlterarValorMensalWithHttpInfo(clienteId, alterarValorMensalRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Alterar valor mensal Altera o valor mensal de aporte do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AlterarValorMensalResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<AlterarValorMensalResponse> AlterarValorMensalWithHttpInfo(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0)
        {
            // verify the required parameter 'alterarValorMensalRequest' is set
            if (alterarValorMensalRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'alterarValorMensalRequest' when calling ClientesApi->AlterarValorMensal");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter
            localVarRequestOptions.Data = alterarValorMensalRequest;

            localVarRequestOptions.Operation = "ClientesApi.AlterarValorMensal";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Put<AlterarValorMensalResponse>("/api/clientes/{clienteId}/valor-mensal", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AlterarValorMensal", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Alterar valor mensal Altera o valor mensal de aporte do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AlterarValorMensalResponse</returns>
        public async System.Threading.Tasks.Task<AlterarValorMensalResponse> AlterarValorMensalAsync(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<AlterarValorMensalResponse> localVarResponse = await AlterarValorMensalWithHttpInfoAsync(clienteId, alterarValorMensalRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Alterar valor mensal Altera o valor mensal de aporte do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="alterarValorMensalRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AlterarValorMensalResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<AlterarValorMensalResponse>> AlterarValorMensalWithHttpInfoAsync(long clienteId, AlterarValorMensalRequest alterarValorMensalRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'alterarValorMensalRequest' is set
            if (alterarValorMensalRequest == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'alterarValorMensalRequest' when calling ClientesApi->AlterarValorMensal");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter
            localVarRequestOptions.Data = alterarValorMensalRequest;

            localVarRequestOptions.Operation = "ClientesApi.AlterarValorMensal";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<AlterarValorMensalResponse>("/api/clientes/{clienteId}/valor-mensal", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("AlterarValorMensal", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Consultar carteira (custódia) Retorna a carteira de ativos do cliente em custódia
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CarteiraResponse</returns>
        public CarteiraResponse ConsultarCarteira(long clienteId, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<CarteiraResponse> localVarResponse = ConsultarCarteiraWithHttpInfo(clienteId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Consultar carteira (custódia) Retorna a carteira de ativos do cliente em custódia
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CarteiraResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<CarteiraResponse> ConsultarCarteiraWithHttpInfo(long clienteId, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter

            localVarRequestOptions.Operation = "ClientesApi.ConsultarCarteira";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<CarteiraResponse>("/api/clientes/{clienteId}/carteira", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConsultarCarteira", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Consultar carteira (custódia) Retorna a carteira de ativos do cliente em custódia
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CarteiraResponse</returns>
        public async System.Threading.Tasks.Task<CarteiraResponse> ConsultarCarteiraAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<CarteiraResponse> localVarResponse = await ConsultarCarteiraWithHttpInfoAsync(clienteId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Consultar carteira (custódia) Retorna a carteira de ativos do cliente em custódia
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CarteiraResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<CarteiraResponse>> ConsultarCarteiraWithHttpInfoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter

            localVarRequestOptions.Operation = "ClientesApi.ConsultarCarteira";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<CarteiraResponse>("/api/clientes/{clienteId}/carteira", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConsultarCarteira", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Consultar rentabilidade detalhada Retorna a rentabilidade detalhada do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RentabilidadeResponse</returns>
        public RentabilidadeResponse ConsultarRentabilidade(long clienteId, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<RentabilidadeResponse> localVarResponse = ConsultarRentabilidadeWithHttpInfo(clienteId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Consultar rentabilidade detalhada Retorna a rentabilidade detalhada do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RentabilidadeResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<RentabilidadeResponse> ConsultarRentabilidadeWithHttpInfo(long clienteId, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter

            localVarRequestOptions.Operation = "ClientesApi.ConsultarRentabilidade";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<RentabilidadeResponse>("/api/clientes/{clienteId}/rentabilidade", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConsultarRentabilidade", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Consultar rentabilidade detalhada Retorna a rentabilidade detalhada do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RentabilidadeResponse</returns>
        public async System.Threading.Tasks.Task<RentabilidadeResponse> ConsultarRentabilidadeAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<RentabilidadeResponse> localVarResponse = await ConsultarRentabilidadeWithHttpInfoAsync(clienteId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Consultar rentabilidade detalhada Retorna a rentabilidade detalhada do cliente
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RentabilidadeResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<RentabilidadeResponse>> ConsultarRentabilidadeWithHttpInfoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter

            localVarRequestOptions.Operation = "ClientesApi.ConsultarRentabilidade";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RentabilidadeResponse>("/api/clientes/{clienteId}/rentabilidade", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConsultarRentabilidade", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sair do produto Permite que um cliente saia do produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SaidaResponse</returns>
        public SaidaResponse SairProduto(long clienteId, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<SaidaResponse> localVarResponse = SairProdutoWithHttpInfo(clienteId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sair do produto Permite que um cliente saia do produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SaidaResponse</returns>
        public Org.OpenAPITools.Client.ApiResponse<SaidaResponse> SairProdutoWithHttpInfo(long clienteId, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter

            localVarRequestOptions.Operation = "ClientesApi.SairProduto";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<SaidaResponse>("/api/clientes/{clienteId}/saida", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SairProduto", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Sair do produto Permite que um cliente saia do produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SaidaResponse</returns>
        public async System.Threading.Tasks.Task<SaidaResponse> SairProdutoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<SaidaResponse> localVarResponse = await SairProdutoWithHttpInfoAsync(clienteId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Sair do produto Permite que um cliente saia do produto de compra programada
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="clienteId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SaidaResponse)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<SaidaResponse>> SairProdutoWithHttpInfoAsync(long clienteId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("clienteId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(clienteId)); // path parameter

            localVarRequestOptions.Operation = "ClientesApi.SairProduto";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SaidaResponse>("/api/clientes/{clienteId}/saida", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SairProduto", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
