/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing AdministrativoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AdministrativoApiTests : IDisposable
    {
        private AdministrativoApi instance;

        public AdministrativoApiTests()
        {
            instance = new AdministrativoApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdministrativoApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AdministrativoApi
            //Assert.IsType<AdministrativoApi>(instance);
        }

        /// <summary>
        /// Test CadastrarCesta
        /// </summary>
        [Fact]
        public void CadastrarCestaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CestaRequest cestaRequest = null;
            //var response = instance.CadastrarCesta(cestaRequest);
            //Assert.IsType<CadastrarCesta201Response>(response);
        }

        /// <summary>
        /// Test ConsultarCestaAtual
        /// </summary>
        [Fact]
        public void ConsultarCestaAtualTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ConsultarCestaAtual();
            //Assert.IsType<CestaAtualResponse>(response);
        }

        /// <summary>
        /// Test ConsultarHistoricoCestas
        /// </summary>
        [Fact]
        public void ConsultarHistoricoCestasTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ConsultarHistoricoCestas();
            //Assert.IsType<HistoricoCestasResponse>(response);
        }
    }
}
