/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ClientesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ClientesApiTests : IDisposable
    {
        private ClientesApi instance;

        public ClientesApiTests()
        {
            instance = new ClientesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ClientesApi
            //Assert.IsType<ClientesApi>(instance);
        }

        /// <summary>
        /// Test AderirProduto
        /// </summary>
        [Fact]
        public void AderirProdutoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AdesaoRequest adesaoRequest = null;
            //var response = instance.AderirProduto(adesaoRequest);
            //Assert.IsType<AdesaoResponse>(response);
        }

        /// <summary>
        /// Test AlterarValorMensal
        /// </summary>
        [Fact]
        public void AlterarValorMensalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long clienteId = null;
            //AlterarValorMensalRequest alterarValorMensalRequest = null;
            //var response = instance.AlterarValorMensal(clienteId, alterarValorMensalRequest);
            //Assert.IsType<AlterarValorMensalResponse>(response);
        }

        /// <summary>
        /// Test ConsultarCarteira
        /// </summary>
        [Fact]
        public void ConsultarCarteiraTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long clienteId = null;
            //var response = instance.ConsultarCarteira(clienteId);
            //Assert.IsType<CarteiraResponse>(response);
        }

        /// <summary>
        /// Test ConsultarRentabilidade
        /// </summary>
        [Fact]
        public void ConsultarRentabilidadeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long clienteId = null;
            //var response = instance.ConsultarRentabilidade(clienteId);
            //Assert.IsType<RentabilidadeResponse>(response);
        }

        /// <summary>
        /// Test SairProduto
        /// </summary>
        [Fact]
        public void SairProdutoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long clienteId = null;
            //var response = instance.SairProduto(clienteId);
            //Assert.IsType<SaidaResponse>(response);
        }
    }
}
