/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ContaMasterApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ContaMasterApiTests : IDisposable
    {
        private ContaMasterApi instance;

        public ContaMasterApiTests()
        {
            instance = new ContaMasterApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContaMasterApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ContaMasterApi
            //Assert.IsType<ContaMasterApi>(instance);
        }

        /// <summary>
        /// Test ConsultarCustodiaMaster
        /// </summary>
        [Fact]
        public void ConsultarCustodiaMasterTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ConsultarCustodiaMaster();
            //Assert.IsType<CustodiaMasterResponse>(response);
        }
    }
}
