/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing MotorDeCompraApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MotorDeCompraApiTests : IDisposable
    {
        private MotorDeCompraApi instance;

        public MotorDeCompraApiTests()
        {
            instance = new MotorDeCompraApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MotorDeCompraApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MotorDeCompraApi
            //Assert.IsType<MotorDeCompraApi>(instance);
        }

        /// <summary>
        /// Test ExecutarCompra
        /// </summary>
        [Fact]
        public void ExecutarCompraTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ExecutarCompraRequest executarCompraRequest = null;
            //var response = instance.ExecutarCompra(executarCompraRequest);
            //Assert.IsType<ExecutarCompraResponse>(response);
        }
    }
}
