/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AdesaoRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdesaoRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdesaoRequest
        //private AdesaoRequest instance;

        public AdesaoRequestTests()
        {
            // TODO uncomment below to create an instance of AdesaoRequest
            //instance = new AdesaoRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdesaoRequest
        /// </summary>
        [Fact]
        public void AdesaoRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdesaoRequest
            //Assert.IsType<AdesaoRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'Cpf'
        /// </summary>
        [Fact]
        public void CpfTest()
        {
            // TODO unit test for the property 'Cpf'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'ValorMensal'
        /// </summary>
        [Fact]
        public void ValorMensalTest()
        {
            // TODO unit test for the property 'ValorMensal'
        }
    }
}
