/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AlterarValorMensalRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlterarValorMensalRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlterarValorMensalRequest
        //private AlterarValorMensalRequest instance;

        public AlterarValorMensalRequestTests()
        {
            // TODO uncomment below to create an instance of AlterarValorMensalRequest
            //instance = new AlterarValorMensalRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlterarValorMensalRequest
        /// </summary>
        [Fact]
        public void AlterarValorMensalRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlterarValorMensalRequest
            //Assert.IsType<AlterarValorMensalRequest>(instance);
        }

        /// <summary>
        /// Test the property 'NovoValorMensal'
        /// </summary>
        [Fact]
        public void NovoValorMensalTest()
        {
            // TODO unit test for the property 'NovoValorMensal'
        }
    }
}
