/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AlterarValorMensalResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AlterarValorMensalResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AlterarValorMensalResponse
        //private AlterarValorMensalResponse instance;

        public AlterarValorMensalResponseTests()
        {
            // TODO uncomment below to create an instance of AlterarValorMensalResponse
            //instance = new AlterarValorMensalResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlterarValorMensalResponse
        /// </summary>
        [Fact]
        public void AlterarValorMensalResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AlterarValorMensalResponse
            //Assert.IsType<AlterarValorMensalResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ClienteId'
        /// </summary>
        [Fact]
        public void ClienteIdTest()
        {
            // TODO unit test for the property 'ClienteId'
        }

        /// <summary>
        /// Test the property 'ValorMensalAnterior'
        /// </summary>
        [Fact]
        public void ValorMensalAnteriorTest()
        {
            // TODO unit test for the property 'ValorMensalAnterior'
        }

        /// <summary>
        /// Test the property 'ValorMensalNovo'
        /// </summary>
        [Fact]
        public void ValorMensalNovoTest()
        {
            // TODO unit test for the property 'ValorMensalNovo'
        }

        /// <summary>
        /// Test the property 'DataAlteracao'
        /// </summary>
        [Fact]
        public void DataAlteracaoTest()
        {
            // TODO unit test for the property 'DataAlteracao'
        }

        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Fact]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }
    }
}
