/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AtivoCarteira
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AtivoCarteiraTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AtivoCarteira
        //private AtivoCarteira instance;

        public AtivoCarteiraTests()
        {
            // TODO uncomment below to create an instance of AtivoCarteira
            //instance = new AtivoCarteira();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AtivoCarteira
        /// </summary>
        [Fact]
        public void AtivoCarteiraInstanceTest()
        {
            // TODO uncomment below to test "IsType" AtivoCarteira
            //Assert.IsType<AtivoCarteira>(instance);
        }

        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Fact]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }

        /// <summary>
        /// Test the property 'Quantidade'
        /// </summary>
        [Fact]
        public void QuantidadeTest()
        {
            // TODO unit test for the property 'Quantidade'
        }

        /// <summary>
        /// Test the property 'PrecoMedio'
        /// </summary>
        [Fact]
        public void PrecoMedioTest()
        {
            // TODO unit test for the property 'PrecoMedio'
        }

        /// <summary>
        /// Test the property 'CotacaoAtual'
        /// </summary>
        [Fact]
        public void CotacaoAtualTest()
        {
            // TODO unit test for the property 'CotacaoAtual'
        }

        /// <summary>
        /// Test the property 'ValorAtual'
        /// </summary>
        [Fact]
        public void ValorAtualTest()
        {
            // TODO unit test for the property 'ValorAtual'
        }

        /// <summary>
        /// Test the property 'Pl'
        /// </summary>
        [Fact]
        public void PlTest()
        {
            // TODO unit test for the property 'Pl'
        }

        /// <summary>
        /// Test the property 'PlPercentual'
        /// </summary>
        [Fact]
        public void PlPercentualTest()
        {
            // TODO unit test for the property 'PlPercentual'
        }

        /// <summary>
        /// Test the property 'ComposicaoCarteira'
        /// </summary>
        [Fact]
        public void ComposicaoCarteiraTest()
        {
            // TODO unit test for the property 'ComposicaoCarteira'
        }
    }
}
