/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CarteiraResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CarteiraResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CarteiraResponse
        //private CarteiraResponse instance;

        public CarteiraResponseTests()
        {
            // TODO uncomment below to create an instance of CarteiraResponse
            //instance = new CarteiraResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CarteiraResponse
        /// </summary>
        [Fact]
        public void CarteiraResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CarteiraResponse
            //Assert.IsType<CarteiraResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ClienteId'
        /// </summary>
        [Fact]
        public void ClienteIdTest()
        {
            // TODO unit test for the property 'ClienteId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'ContaGrafica'
        /// </summary>
        [Fact]
        public void ContaGraficaTest()
        {
            // TODO unit test for the property 'ContaGrafica'
        }

        /// <summary>
        /// Test the property 'DataConsulta'
        /// </summary>
        [Fact]
        public void DataConsultaTest()
        {
            // TODO unit test for the property 'DataConsulta'
        }

        /// <summary>
        /// Test the property 'Resumo'
        /// </summary>
        [Fact]
        public void ResumoTest()
        {
            // TODO unit test for the property 'Resumo'
        }

        /// <summary>
        /// Test the property 'Ativos'
        /// </summary>
        [Fact]
        public void AtivosTest()
        {
            // TODO unit test for the property 'Ativos'
        }
    }
}
