/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CestaHistorico
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CestaHistoricoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CestaHistorico
        //private CestaHistorico instance;

        public CestaHistoricoTests()
        {
            // TODO uncomment below to create an instance of CestaHistorico
            //instance = new CestaHistorico();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CestaHistorico
        /// </summary>
        [Fact]
        public void CestaHistoricoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CestaHistorico
            //Assert.IsType<CestaHistorico>(instance);
        }

        /// <summary>
        /// Test the property 'CestaId'
        /// </summary>
        [Fact]
        public void CestaIdTest()
        {
            // TODO unit test for the property 'CestaId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'Ativa'
        /// </summary>
        [Fact]
        public void AtivaTest()
        {
            // TODO unit test for the property 'Ativa'
        }

        /// <summary>
        /// Test the property 'DataCriacao'
        /// </summary>
        [Fact]
        public void DataCriacaoTest()
        {
            // TODO unit test for the property 'DataCriacao'
        }

        /// <summary>
        /// Test the property 'DataDesativacao'
        /// </summary>
        [Fact]
        public void DataDesativacaoTest()
        {
            // TODO unit test for the property 'DataDesativacao'
        }

        /// <summary>
        /// Test the property 'Itens'
        /// </summary>
        [Fact]
        public void ItensTest()
        {
            // TODO unit test for the property 'Itens'
        }
    }
}
