/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CestaResponseSimples
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CestaResponseSimplesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CestaResponseSimples
        //private CestaResponseSimples instance;

        public CestaResponseSimplesTests()
        {
            // TODO uncomment below to create an instance of CestaResponseSimples
            //instance = new CestaResponseSimples();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CestaResponseSimples
        /// </summary>
        [Fact]
        public void CestaResponseSimplesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CestaResponseSimples
            //Assert.IsType<CestaResponseSimples>(instance);
        }

        /// <summary>
        /// Test the property 'CestaId'
        /// </summary>
        [Fact]
        public void CestaIdTest()
        {
            // TODO unit test for the property 'CestaId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'Ativa'
        /// </summary>
        [Fact]
        public void AtivaTest()
        {
            // TODO unit test for the property 'Ativa'
        }

        /// <summary>
        /// Test the property 'DataCriacao'
        /// </summary>
        [Fact]
        public void DataCriacaoTest()
        {
            // TODO unit test for the property 'DataCriacao'
        }

        /// <summary>
        /// Test the property 'Itens'
        /// </summary>
        [Fact]
        public void ItensTest()
        {
            // TODO unit test for the property 'Itens'
        }

        /// <summary>
        /// Test the property 'RebalanceamentoDisparado'
        /// </summary>
        [Fact]
        public void RebalanceamentoDisparadoTest()
        {
            // TODO unit test for the property 'RebalanceamentoDisparado'
        }

        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Fact]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }
    }
}
