/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CestaAnteriorDesativada
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CestaAnteriorDesativadaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CestaAnteriorDesativada
        //private CestaAnteriorDesativada instance;

        public CestaAnteriorDesativadaTests()
        {
            // TODO uncomment below to create an instance of CestaAnteriorDesativada
            //instance = new CestaAnteriorDesativada();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CestaAnteriorDesativada
        /// </summary>
        [Fact]
        public void CestaAnteriorDesativadaInstanceTest()
        {
            // TODO uncomment below to test "IsType" CestaAnteriorDesativada
            //Assert.IsType<CestaAnteriorDesativada>(instance);
        }

        /// <summary>
        /// Test the property 'CestaId'
        /// </summary>
        [Fact]
        public void CestaIdTest()
        {
            // TODO unit test for the property 'CestaId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'DataDesativacao'
        /// </summary>
        [Fact]
        public void DataDesativacaoTest()
        {
            // TODO unit test for the property 'DataDesativacao'
        }
    }
}
