/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CestaResponseComRebalanceamento
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CestaResponseComRebalanceamentoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CestaResponseComRebalanceamento
        //private CestaResponseComRebalanceamento instance;

        public CestaResponseComRebalanceamentoTests()
        {
            // TODO uncomment below to create an instance of CestaResponseComRebalanceamento
            //instance = new CestaResponseComRebalanceamento();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CestaResponseComRebalanceamento
        /// </summary>
        [Fact]
        public void CestaResponseComRebalanceamentoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CestaResponseComRebalanceamento
            //Assert.IsType<CestaResponseComRebalanceamento>(instance);
        }

        /// <summary>
        /// Test the property 'CestaId'
        /// </summary>
        [Fact]
        public void CestaIdTest()
        {
            // TODO unit test for the property 'CestaId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'Ativa'
        /// </summary>
        [Fact]
        public void AtivaTest()
        {
            // TODO unit test for the property 'Ativa'
        }

        /// <summary>
        /// Test the property 'DataCriacao'
        /// </summary>
        [Fact]
        public void DataCriacaoTest()
        {
            // TODO unit test for the property 'DataCriacao'
        }

        /// <summary>
        /// Test the property 'Itens'
        /// </summary>
        [Fact]
        public void ItensTest()
        {
            // TODO unit test for the property 'Itens'
        }

        /// <summary>
        /// Test the property 'CestaAnteriorDesativada'
        /// </summary>
        [Fact]
        public void CestaAnteriorDesativadaTest()
        {
            // TODO unit test for the property 'CestaAnteriorDesativada'
        }

        /// <summary>
        /// Test the property 'RebalanceamentoDisparado'
        /// </summary>
        [Fact]
        public void RebalanceamentoDisparadoTest()
        {
            // TODO unit test for the property 'RebalanceamentoDisparado'
        }

        /// <summary>
        /// Test the property 'AtivosRemovidos'
        /// </summary>
        [Fact]
        public void AtivosRemovidosTest()
        {
            // TODO unit test for the property 'AtivosRemovidos'
        }

        /// <summary>
        /// Test the property 'AtivosAdicionados'
        /// </summary>
        [Fact]
        public void AtivosAdicionadosTest()
        {
            // TODO unit test for the property 'AtivosAdicionados'
        }

        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Fact]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }
    }
}
