/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CestaRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CestaRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CestaRequest
        //private CestaRequest instance;

        public CestaRequestTests()
        {
            // TODO uncomment below to create an instance of CestaRequest
            //instance = new CestaRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CestaRequest
        /// </summary>
        [Fact]
        public void CestaRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CestaRequest
            //Assert.IsType<CestaRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'Itens'
        /// </summary>
        [Fact]
        public void ItensTest()
        {
            // TODO unit test for the property 'Itens'
        }
    }
}
