/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContaMasterInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContaMasterInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContaMasterInfo
        //private ContaMasterInfo instance;

        public ContaMasterInfoTests()
        {
            // TODO uncomment below to create an instance of ContaMasterInfo
            //instance = new ContaMasterInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContaMasterInfo
        /// </summary>
        [Fact]
        public void ContaMasterInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContaMasterInfo
            //Assert.IsType<ContaMasterInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'NumeroConta'
        /// </summary>
        [Fact]
        public void NumeroContaTest()
        {
            // TODO unit test for the property 'NumeroConta'
        }

        /// <summary>
        /// Test the property 'Tipo'
        /// </summary>
        [Fact]
        public void TipoTest()
        {
            // TODO unit test for the property 'Tipo'
        }
    }
}
