/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContaGrafica
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContaGraficaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContaGrafica
        //private ContaGrafica instance;

        public ContaGraficaTests()
        {
            // TODO uncomment below to create an instance of ContaGrafica
            //instance = new ContaGrafica();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContaGrafica
        /// </summary>
        [Fact]
        public void ContaGraficaInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContaGrafica
            //Assert.IsType<ContaGrafica>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'NumeroConta'
        /// </summary>
        [Fact]
        public void NumeroContaTest()
        {
            // TODO unit test for the property 'NumeroConta'
        }

        /// <summary>
        /// Test the property 'Tipo'
        /// </summary>
        [Fact]
        public void TipoTest()
        {
            // TODO unit test for the property 'Tipo'
        }

        /// <summary>
        /// Test the property 'DataCriacao'
        /// </summary>
        [Fact]
        public void DataCriacaoTest()
        {
            // TODO unit test for the property 'DataCriacao'
        }
    }
}
