/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CustodiaMasterResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustodiaMasterResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustodiaMasterResponse
        //private CustodiaMasterResponse instance;

        public CustodiaMasterResponseTests()
        {
            // TODO uncomment below to create an instance of CustodiaMasterResponse
            //instance = new CustodiaMasterResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustodiaMasterResponse
        /// </summary>
        [Fact]
        public void CustodiaMasterResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustodiaMasterResponse
            //Assert.IsType<CustodiaMasterResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ContaMaster'
        /// </summary>
        [Fact]
        public void ContaMasterTest()
        {
            // TODO unit test for the property 'ContaMaster'
        }

        /// <summary>
        /// Test the property 'Custodia'
        /// </summary>
        [Fact]
        public void CustodiaTest()
        {
            // TODO unit test for the property 'Custodia'
        }

        /// <summary>
        /// Test the property 'ValorTotalResiduo'
        /// </summary>
        [Fact]
        public void ValorTotalResiduoTest()
        {
            // TODO unit test for the property 'ValorTotalResiduo'
        }
    }
}
