/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DistribuicaoCliente
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DistribuicaoClienteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DistribuicaoCliente
        //private DistribuicaoCliente instance;

        public DistribuicaoClienteTests()
        {
            // TODO uncomment below to create an instance of DistribuicaoCliente
            //instance = new DistribuicaoCliente();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DistribuicaoCliente
        /// </summary>
        [Fact]
        public void DistribuicaoClienteInstanceTest()
        {
            // TODO uncomment below to test "IsType" DistribuicaoCliente
            //Assert.IsType<DistribuicaoCliente>(instance);
        }

        /// <summary>
        /// Test the property 'ClienteId'
        /// </summary>
        [Fact]
        public void ClienteIdTest()
        {
            // TODO unit test for the property 'ClienteId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'ValorAporte'
        /// </summary>
        [Fact]
        public void ValorAporteTest()
        {
            // TODO unit test for the property 'ValorAporte'
        }

        /// <summary>
        /// Test the property 'Ativos'
        /// </summary>
        [Fact]
        public void AtivosTest()
        {
            // TODO unit test for the property 'Ativos'
        }
    }
}
