/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EvolucaoCarteira
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EvolucaoCarteiraTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EvolucaoCarteira
        //private EvolucaoCarteira instance;

        public EvolucaoCarteiraTests()
        {
            // TODO uncomment below to create an instance of EvolucaoCarteira
            //instance = new EvolucaoCarteira();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EvolucaoCarteira
        /// </summary>
        [Fact]
        public void EvolucaoCarteiraInstanceTest()
        {
            // TODO uncomment below to test "IsType" EvolucaoCarteira
            //Assert.IsType<EvolucaoCarteira>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'ValorCarteira'
        /// </summary>
        [Fact]
        public void ValorCarteiraTest()
        {
            // TODO unit test for the property 'ValorCarteira'
        }

        /// <summary>
        /// Test the property 'ValorInvestido'
        /// </summary>
        [Fact]
        public void ValorInvestidoTest()
        {
            // TODO unit test for the property 'ValorInvestido'
        }

        /// <summary>
        /// Test the property 'Rentabilidade'
        /// </summary>
        [Fact]
        public void RentabilidadeTest()
        {
            // TODO unit test for the property 'Rentabilidade'
        }
    }
}
