/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ExecutarCompraRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExecutarCompraRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExecutarCompraRequest
        //private ExecutarCompraRequest instance;

        public ExecutarCompraRequestTests()
        {
            // TODO uncomment below to create an instance of ExecutarCompraRequest
            //instance = new ExecutarCompraRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExecutarCompraRequest
        /// </summary>
        [Fact]
        public void ExecutarCompraRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExecutarCompraRequest
            //Assert.IsType<ExecutarCompraRequest>(instance);
        }

        /// <summary>
        /// Test the property 'DataReferencia'
        /// </summary>
        [Fact]
        public void DataReferenciaTest()
        {
            // TODO unit test for the property 'DataReferencia'
        }
    }
}
