/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ExecutarCompraResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExecutarCompraResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExecutarCompraResponse
        //private ExecutarCompraResponse instance;

        public ExecutarCompraResponseTests()
        {
            // TODO uncomment below to create an instance of ExecutarCompraResponse
            //instance = new ExecutarCompraResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExecutarCompraResponse
        /// </summary>
        [Fact]
        public void ExecutarCompraResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExecutarCompraResponse
            //Assert.IsType<ExecutarCompraResponse>(instance);
        }

        /// <summary>
        /// Test the property 'DataExecucao'
        /// </summary>
        [Fact]
        public void DataExecucaoTest()
        {
            // TODO unit test for the property 'DataExecucao'
        }

        /// <summary>
        /// Test the property 'TotalClientes'
        /// </summary>
        [Fact]
        public void TotalClientesTest()
        {
            // TODO unit test for the property 'TotalClientes'
        }

        /// <summary>
        /// Test the property 'TotalConsolidado'
        /// </summary>
        [Fact]
        public void TotalConsolidadoTest()
        {
            // TODO unit test for the property 'TotalConsolidado'
        }

        /// <summary>
        /// Test the property 'OrdensCompra'
        /// </summary>
        [Fact]
        public void OrdensCompraTest()
        {
            // TODO unit test for the property 'OrdensCompra'
        }

        /// <summary>
        /// Test the property 'Distribuicoes'
        /// </summary>
        [Fact]
        public void DistribuicoesTest()
        {
            // TODO unit test for the property 'Distribuicoes'
        }

        /// <summary>
        /// Test the property 'ResiduosCustMaster'
        /// </summary>
        [Fact]
        public void ResiduosCustMasterTest()
        {
            // TODO unit test for the property 'ResiduosCustMaster'
        }

        /// <summary>
        /// Test the property 'EventosIRPublicados'
        /// </summary>
        [Fact]
        public void EventosIRPublicadosTest()
        {
            // TODO unit test for the property 'EventosIRPublicados'
        }

        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Fact]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }
    }
}
