/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing HistoricoCestasResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HistoricoCestasResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HistoricoCestasResponse
        //private HistoricoCestasResponse instance;

        public HistoricoCestasResponseTests()
        {
            // TODO uncomment below to create an instance of HistoricoCestasResponse
            //instance = new HistoricoCestasResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HistoricoCestasResponse
        /// </summary>
        [Fact]
        public void HistoricoCestasResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" HistoricoCestasResponse
            //Assert.IsType<HistoricoCestasResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Cestas'
        /// </summary>
        [Fact]
        public void CestasTest()
        {
            // TODO unit test for the property 'Cestas'
        }
    }
}
