/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing HistoricoAporte
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HistoricoAporteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HistoricoAporte
        //private HistoricoAporte instance;

        public HistoricoAporteTests()
        {
            // TODO uncomment below to create an instance of HistoricoAporte
            //instance = new HistoricoAporte();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HistoricoAporte
        /// </summary>
        [Fact]
        public void HistoricoAporteInstanceTest()
        {
            // TODO uncomment below to test "IsType" HistoricoAporte
            //Assert.IsType<HistoricoAporte>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Valor'
        /// </summary>
        [Fact]
        public void ValorTest()
        {
            // TODO unit test for the property 'Valor'
        }

        /// <summary>
        /// Test the property 'Parcela'
        /// </summary>
        [Fact]
        public void ParcelaTest()
        {
            // TODO unit test for the property 'Parcela'
        }
    }
}
