/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ItemCestaComCotacao
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemCestaComCotacaoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemCestaComCotacao
        //private ItemCestaComCotacao instance;

        public ItemCestaComCotacaoTests()
        {
            // TODO uncomment below to create an instance of ItemCestaComCotacao
            //instance = new ItemCestaComCotacao();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemCestaComCotacao
        /// </summary>
        [Fact]
        public void ItemCestaComCotacaoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemCestaComCotacao
            //Assert.IsType<ItemCestaComCotacao>(instance);
        }

        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Fact]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }

        /// <summary>
        /// Test the property 'Percentual'
        /// </summary>
        [Fact]
        public void PercentualTest()
        {
            // TODO unit test for the property 'Percentual'
        }

        /// <summary>
        /// Test the property 'CotacaoAtual'
        /// </summary>
        [Fact]
        public void CotacaoAtualTest()
        {
            // TODO unit test for the property 'CotacaoAtual'
        }
    }
}
