/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrdemCompra
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrdemCompraTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrdemCompra
        //private OrdemCompra instance;

        public OrdemCompraTests()
        {
            // TODO uncomment below to create an instance of OrdemCompra
            //instance = new OrdemCompra();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrdemCompra
        /// </summary>
        [Fact]
        public void OrdemCompraInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrdemCompra
            //Assert.IsType<OrdemCompra>(instance);
        }

        /// <summary>
        /// Test the property 'Ticker'
        /// </summary>
        [Fact]
        public void TickerTest()
        {
            // TODO unit test for the property 'Ticker'
        }

        /// <summary>
        /// Test the property 'QuantidadeTotal'
        /// </summary>
        [Fact]
        public void QuantidadeTotalTest()
        {
            // TODO unit test for the property 'QuantidadeTotal'
        }

        /// <summary>
        /// Test the property 'Detalhes'
        /// </summary>
        [Fact]
        public void DetalhesTest()
        {
            // TODO unit test for the property 'Detalhes'
        }

        /// <summary>
        /// Test the property 'PrecoUnitario'
        /// </summary>
        [Fact]
        public void PrecoUnitarioTest()
        {
            // TODO unit test for the property 'PrecoUnitario'
        }

        /// <summary>
        /// Test the property 'ValorTotal'
        /// </summary>
        [Fact]
        public void ValorTotalTest()
        {
            // TODO unit test for the property 'ValorTotal'
        }
    }
}
