/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing RentabilidadeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RentabilidadeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RentabilidadeResponse
        //private RentabilidadeResponse instance;

        public RentabilidadeResponseTests()
        {
            // TODO uncomment below to create an instance of RentabilidadeResponse
            //instance = new RentabilidadeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RentabilidadeResponse
        /// </summary>
        [Fact]
        public void RentabilidadeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RentabilidadeResponse
            //Assert.IsType<RentabilidadeResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ClienteId'
        /// </summary>
        [Fact]
        public void ClienteIdTest()
        {
            // TODO unit test for the property 'ClienteId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'DataConsulta'
        /// </summary>
        [Fact]
        public void DataConsultaTest()
        {
            // TODO unit test for the property 'DataConsulta'
        }

        /// <summary>
        /// Test the property 'Rentabilidade'
        /// </summary>
        [Fact]
        public void RentabilidadeTest()
        {
            // TODO unit test for the property 'Rentabilidade'
        }

        /// <summary>
        /// Test the property 'HistoricoAportes'
        /// </summary>
        [Fact]
        public void HistoricoAportesTest()
        {
            // TODO unit test for the property 'HistoricoAportes'
        }

        /// <summary>
        /// Test the property 'EvolucaoCarteira'
        /// </summary>
        [Fact]
        public void EvolucaoCarteiraTest()
        {
            // TODO unit test for the property 'EvolucaoCarteira'
        }
    }
}
