/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ResumoCarteira
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResumoCarteiraTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResumoCarteira
        //private ResumoCarteira instance;

        public ResumoCarteiraTests()
        {
            // TODO uncomment below to create an instance of ResumoCarteira
            //instance = new ResumoCarteira();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResumoCarteira
        /// </summary>
        [Fact]
        public void ResumoCarteiraInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResumoCarteira
            //Assert.IsType<ResumoCarteira>(instance);
        }

        /// <summary>
        /// Test the property 'ValorTotalInvestido'
        /// </summary>
        [Fact]
        public void ValorTotalInvestidoTest()
        {
            // TODO unit test for the property 'ValorTotalInvestido'
        }

        /// <summary>
        /// Test the property 'ValorAtualCarteira'
        /// </summary>
        [Fact]
        public void ValorAtualCarteiraTest()
        {
            // TODO unit test for the property 'ValorAtualCarteira'
        }

        /// <summary>
        /// Test the property 'PlTotal'
        /// </summary>
        [Fact]
        public void PlTotalTest()
        {
            // TODO unit test for the property 'PlTotal'
        }

        /// <summary>
        /// Test the property 'RentabilidadePercentual'
        /// </summary>
        [Fact]
        public void RentabilidadePercentualTest()
        {
            // TODO unit test for the property 'RentabilidadePercentual'
        }
    }
}
