/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SaidaResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SaidaResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SaidaResponse
        //private SaidaResponse instance;

        public SaidaResponseTests()
        {
            // TODO uncomment below to create an instance of SaidaResponse
            //instance = new SaidaResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SaidaResponse
        /// </summary>
        [Fact]
        public void SaidaResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SaidaResponse
            //Assert.IsType<SaidaResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ClienteId'
        /// </summary>
        [Fact]
        public void ClienteIdTest()
        {
            // TODO unit test for the property 'ClienteId'
        }

        /// <summary>
        /// Test the property 'Nome'
        /// </summary>
        [Fact]
        public void NomeTest()
        {
            // TODO unit test for the property 'Nome'
        }

        /// <summary>
        /// Test the property 'Ativo'
        /// </summary>
        [Fact]
        public void AtivoTest()
        {
            // TODO unit test for the property 'Ativo'
        }

        /// <summary>
        /// Test the property 'DataSaida'
        /// </summary>
        [Fact]
        public void DataSaidaTest()
        {
            // TODO unit test for the property 'DataSaida'
        }

        /// <summary>
        /// Test the property 'Mensagem'
        /// </summary>
        [Fact]
        public void MensagemTest()
        {
            // TODO unit test for the property 'Mensagem'
        }
    }
}
