/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AdesaoRequest
    /// </summary>
    [DataContract(Name = "AdesaoRequest")]
    public partial class AdesaoRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdesaoRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AdesaoRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AdesaoRequest" /> class.
        /// </summary>
        /// <param name="nome">nome (required).</param>
        /// <param name="cpf">cpf (required).</param>
        /// <param name="email">email (required).</param>
        /// <param name="valorMensal">valorMensal (required).</param>
        public AdesaoRequest(string nome = default(string), string cpf = default(string), string email = default(string), double valorMensal = default(double))
        {
            // to ensure "nome" is required (not null)
            if (nome == null)
            {
                throw new ArgumentNullException("nome is a required property for AdesaoRequest and cannot be null");
            }
            this.Nome = nome;
            // to ensure "cpf" is required (not null)
            if (cpf == null)
            {
                throw new ArgumentNullException("cpf is a required property for AdesaoRequest and cannot be null");
            }
            this.Cpf = cpf;
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for AdesaoRequest and cannot be null");
            }
            this.Email = email;
            this.ValorMensal = valorMensal;
        }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        /// <example>Joao da Silva</example>
        [DataMember(Name = "nome", IsRequired = true, EmitDefaultValue = true)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets Cpf
        /// </summary>
        /// <example>12345678901</example>
        [DataMember(Name = "cpf", IsRequired = true, EmitDefaultValue = true)]
        public string Cpf { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /// <example>joao.silva@email.com</example>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets ValorMensal
        /// </summary>
        /// <example>3000.0</example>
        [DataMember(Name = "valorMensal", IsRequired = true, EmitDefaultValue = true)]
        public double ValorMensal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdesaoRequest {\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  Cpf: ").Append(Cpf).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  ValorMensal: ").Append(ValorMensal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Cpf != null) {
                // Cpf (string) pattern
                Regex regexCpf = new Regex(@"^\d{11}$", RegexOptions.CultureInvariant);
                if (!regexCpf.Match(this.Cpf).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Cpf, must match a pattern of " + regexCpf, new [] { "Cpf" });
                }
            }

            // ValorMensal (double) minimum
            if (this.ValorMensal < (double)100.0)
            {
                yield return new ValidationResult("Invalid value for ValorMensal, must be a value greater than or equal to 100.0.", new [] { "ValorMensal" });
            }

            yield break;
        }
    }

}
