/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AdesaoResponse
    /// </summary>
    [DataContract(Name = "AdesaoResponse")]
    public partial class AdesaoResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdesaoResponse" /> class.
        /// </summary>
        /// <param name="clienteId">clienteId.</param>
        /// <param name="nome">nome.</param>
        /// <param name="cpf">cpf.</param>
        /// <param name="email">email.</param>
        /// <param name="valorMensal">valorMensal.</param>
        /// <param name="ativo">ativo.</param>
        /// <param name="dataAdesao">dataAdesao.</param>
        /// <param name="contaGrafica">contaGrafica.</param>
        public AdesaoResponse(long clienteId = default(long), string nome = default(string), string cpf = default(string), string email = default(string), double valorMensal = default(double), bool ativo = default(bool), DateTime dataAdesao = default(DateTime), ContaGrafica contaGrafica = default(ContaGrafica))
        {
            this.ClienteId = clienteId;
            this.Nome = nome;
            this.Cpf = cpf;
            this.Email = email;
            this.ValorMensal = valorMensal;
            this.Ativo = ativo;
            this.DataAdesao = dataAdesao;
            this.ContaGrafica = contaGrafica;
        }

        /// <summary>
        /// Gets or Sets ClienteId
        /// </summary>
        [DataMember(Name = "clienteId", EmitDefaultValue = false)]
        public long ClienteId { get; set; }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", EmitDefaultValue = false)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets Cpf
        /// </summary>
        [DataMember(Name = "cpf", EmitDefaultValue = false)]
        public string Cpf { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets ValorMensal
        /// </summary>
        [DataMember(Name = "valorMensal", EmitDefaultValue = false)]
        public double ValorMensal { get; set; }

        /// <summary>
        /// Gets or Sets Ativo
        /// </summary>
        [DataMember(Name = "ativo", EmitDefaultValue = true)]
        public bool Ativo { get; set; }

        /// <summary>
        /// Gets or Sets DataAdesao
        /// </summary>
        [DataMember(Name = "dataAdesao", EmitDefaultValue = false)]
        public DateTime DataAdesao { get; set; }

        /// <summary>
        /// Gets or Sets ContaGrafica
        /// </summary>
        [DataMember(Name = "contaGrafica", EmitDefaultValue = false)]
        public ContaGrafica ContaGrafica { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AdesaoResponse {\n");
            sb.Append("  ClienteId: ").Append(ClienteId).Append("\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  Cpf: ").Append(Cpf).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  ValorMensal: ").Append(ValorMensal).Append("\n");
            sb.Append("  Ativo: ").Append(Ativo).Append("\n");
            sb.Append("  DataAdesao: ").Append(DataAdesao).Append("\n");
            sb.Append("  ContaGrafica: ").Append(ContaGrafica).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
