/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AlterarValorMensalRequest
    /// </summary>
    [DataContract(Name = "AlterarValorMensalRequest")]
    public partial class AlterarValorMensalRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlterarValorMensalRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AlterarValorMensalRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AlterarValorMensalRequest" /> class.
        /// </summary>
        /// <param name="novoValorMensal">novoValorMensal (required).</param>
        public AlterarValorMensalRequest(double novoValorMensal = default(double))
        {
            this.NovoValorMensal = novoValorMensal;
        }

        /// <summary>
        /// Gets or Sets NovoValorMensal
        /// </summary>
        [DataMember(Name = "novoValorMensal", IsRequired = true, EmitDefaultValue = true)]
        public double NovoValorMensal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlterarValorMensalRequest {\n");
            sb.Append("  NovoValorMensal: ").Append(NovoValorMensal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // NovoValorMensal (double) minimum
            if (this.NovoValorMensal < (double)100.0)
            {
                yield return new ValidationResult("Invalid value for NovoValorMensal, must be a value greater than or equal to 100.0.", new [] { "NovoValorMensal" });
            }

            yield break;
        }
    }

}
