/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AlterarValorMensalResponse
    /// </summary>
    [DataContract(Name = "AlterarValorMensalResponse")]
    public partial class AlterarValorMensalResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlterarValorMensalResponse" /> class.
        /// </summary>
        /// <param name="clienteId">clienteId.</param>
        /// <param name="valorMensalAnterior">valorMensalAnterior.</param>
        /// <param name="valorMensalNovo">valorMensalNovo.</param>
        /// <param name="dataAlteracao">dataAlteracao.</param>
        /// <param name="mensagem">mensagem.</param>
        public AlterarValorMensalResponse(long clienteId = default(long), double valorMensalAnterior = default(double), double valorMensalNovo = default(double), DateTime dataAlteracao = default(DateTime), string mensagem = default(string))
        {
            this.ClienteId = clienteId;
            this.ValorMensalAnterior = valorMensalAnterior;
            this.ValorMensalNovo = valorMensalNovo;
            this.DataAlteracao = dataAlteracao;
            this.Mensagem = mensagem;
        }

        /// <summary>
        /// Gets or Sets ClienteId
        /// </summary>
        [DataMember(Name = "clienteId", EmitDefaultValue = false)]
        public long ClienteId { get; set; }

        /// <summary>
        /// Gets or Sets ValorMensalAnterior
        /// </summary>
        [DataMember(Name = "valorMensalAnterior", EmitDefaultValue = false)]
        public double ValorMensalAnterior { get; set; }

        /// <summary>
        /// Gets or Sets ValorMensalNovo
        /// </summary>
        [DataMember(Name = "valorMensalNovo", EmitDefaultValue = false)]
        public double ValorMensalNovo { get; set; }

        /// <summary>
        /// Gets or Sets DataAlteracao
        /// </summary>
        [DataMember(Name = "dataAlteracao", EmitDefaultValue = false)]
        public DateTime DataAlteracao { get; set; }

        /// <summary>
        /// Gets or Sets Mensagem
        /// </summary>
        [DataMember(Name = "mensagem", EmitDefaultValue = false)]
        public string Mensagem { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AlterarValorMensalResponse {\n");
            sb.Append("  ClienteId: ").Append(ClienteId).Append("\n");
            sb.Append("  ValorMensalAnterior: ").Append(ValorMensalAnterior).Append("\n");
            sb.Append("  ValorMensalNovo: ").Append(ValorMensalNovo).Append("\n");
            sb.Append("  DataAlteracao: ").Append(DataAlteracao).Append("\n");
            sb.Append("  Mensagem: ").Append(Mensagem).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
