/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// AtivoCarteira
    /// </summary>
    [DataContract(Name = "AtivoCarteira")]
    public partial class AtivoCarteira : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AtivoCarteira" /> class.
        /// </summary>
        /// <param name="ticker">ticker.</param>
        /// <param name="quantidade">quantidade.</param>
        /// <param name="precoMedio">precoMedio.</param>
        /// <param name="cotacaoAtual">cotacaoAtual.</param>
        /// <param name="valorAtual">valorAtual.</param>
        /// <param name="pl">pl.</param>
        /// <param name="plPercentual">plPercentual.</param>
        /// <param name="composicaoCarteira">composicaoCarteira.</param>
        public AtivoCarteira(string ticker = default(string), int quantidade = default(int), double precoMedio = default(double), double cotacaoAtual = default(double), double valorAtual = default(double), double pl = default(double), double plPercentual = default(double), double composicaoCarteira = default(double))
        {
            this.Ticker = ticker;
            this.Quantidade = quantidade;
            this.PrecoMedio = precoMedio;
            this.CotacaoAtual = cotacaoAtual;
            this.ValorAtual = valorAtual;
            this.Pl = pl;
            this.PlPercentual = plPercentual;
            this.ComposicaoCarteira = composicaoCarteira;
        }

        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name = "ticker", EmitDefaultValue = false)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets Quantidade
        /// </summary>
        [DataMember(Name = "quantidade", EmitDefaultValue = false)]
        public int Quantidade { get; set; }

        /// <summary>
        /// Gets or Sets PrecoMedio
        /// </summary>
        [DataMember(Name = "precoMedio", EmitDefaultValue = false)]
        public double PrecoMedio { get; set; }

        /// <summary>
        /// Gets or Sets CotacaoAtual
        /// </summary>
        [DataMember(Name = "cotacaoAtual", EmitDefaultValue = false)]
        public double CotacaoAtual { get; set; }

        /// <summary>
        /// Gets or Sets ValorAtual
        /// </summary>
        [DataMember(Name = "valorAtual", EmitDefaultValue = false)]
        public double ValorAtual { get; set; }

        /// <summary>
        /// Gets or Sets Pl
        /// </summary>
        [DataMember(Name = "pl", EmitDefaultValue = false)]
        public double Pl { get; set; }

        /// <summary>
        /// Gets or Sets PlPercentual
        /// </summary>
        [DataMember(Name = "plPercentual", EmitDefaultValue = false)]
        public double PlPercentual { get; set; }

        /// <summary>
        /// Gets or Sets ComposicaoCarteira
        /// </summary>
        [DataMember(Name = "composicaoCarteira", EmitDefaultValue = false)]
        public double ComposicaoCarteira { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AtivoCarteira {\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Quantidade: ").Append(Quantidade).Append("\n");
            sb.Append("  PrecoMedio: ").Append(PrecoMedio).Append("\n");
            sb.Append("  CotacaoAtual: ").Append(CotacaoAtual).Append("\n");
            sb.Append("  ValorAtual: ").Append(ValorAtual).Append("\n");
            sb.Append("  Pl: ").Append(Pl).Append("\n");
            sb.Append("  PlPercentual: ").Append(PlPercentual).Append("\n");
            sb.Append("  ComposicaoCarteira: ").Append(ComposicaoCarteira).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
