/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CadastrarCesta201Response
    /// </summary>
    [JsonConverter(typeof(CadastrarCesta201ResponseJsonConverter))]
    [DataContract(Name = "cadastrarCesta_201_response")]
    public partial class CadastrarCesta201Response : AbstractOpenAPISchema, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CadastrarCesta201Response" /> class
        /// with the <see cref="CestaResponseSimples" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CestaResponseSimples.</param>
        public CadastrarCesta201Response(CestaResponseSimples actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CadastrarCesta201Response" /> class
        /// with the <see cref="CestaResponseComRebalanceamento" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CestaResponseComRebalanceamento.</param>
        public CadastrarCesta201Response(CestaResponseComRebalanceamento actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(CestaResponseComRebalanceamento) || value is CestaResponseComRebalanceamento)
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(CestaResponseSimples) || value is CestaResponseSimples)
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: CestaResponseComRebalanceamento, CestaResponseSimples");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `CestaResponseSimples`. If the actual instance is not `CestaResponseSimples`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CestaResponseSimples</returns>
        public CestaResponseSimples GetCestaResponseSimples()
        {
            return (CestaResponseSimples)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CestaResponseComRebalanceamento`. If the actual instance is not `CestaResponseComRebalanceamento`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CestaResponseComRebalanceamento</returns>
        public CestaResponseComRebalanceamento GetCestaResponseComRebalanceamento()
        {
            return (CestaResponseComRebalanceamento)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CadastrarCesta201Response {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, CadastrarCesta201Response.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of CadastrarCesta201Response
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of CadastrarCesta201Response</returns>
        public static CadastrarCesta201Response FromJson(string jsonString)
        {
            CadastrarCesta201Response newCadastrarCesta201Response = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newCadastrarCesta201Response;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CestaResponseComRebalanceamento).GetProperty("AdditionalProperties") == null)
                {
                    newCadastrarCesta201Response = new CadastrarCesta201Response(JsonConvert.DeserializeObject<CestaResponseComRebalanceamento>(jsonString, CadastrarCesta201Response.SerializerSettings));
                }
                else
                {
                    newCadastrarCesta201Response = new CadastrarCesta201Response(JsonConvert.DeserializeObject<CestaResponseComRebalanceamento>(jsonString, CadastrarCesta201Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CestaResponseComRebalanceamento");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CestaResponseComRebalanceamento: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(CestaResponseSimples).GetProperty("AdditionalProperties") == null)
                {
                    newCadastrarCesta201Response = new CadastrarCesta201Response(JsonConvert.DeserializeObject<CestaResponseSimples>(jsonString, CadastrarCesta201Response.SerializerSettings));
                }
                else
                {
                    newCadastrarCesta201Response = new CadastrarCesta201Response(JsonConvert.DeserializeObject<CestaResponseSimples>(jsonString, CadastrarCesta201Response.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("CestaResponseSimples");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CestaResponseSimples: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newCadastrarCesta201Response;
        }


        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for CadastrarCesta201Response
    /// </summary>
    public class CadastrarCesta201ResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(CadastrarCesta201Response).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch(reader.TokenType) 
            {
                case JsonToken.StartObject:
                    return CadastrarCesta201Response.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return CadastrarCesta201Response.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
