/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CarteiraResponse
    /// </summary>
    [DataContract(Name = "CarteiraResponse")]
    public partial class CarteiraResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CarteiraResponse" /> class.
        /// </summary>
        /// <param name="clienteId">clienteId.</param>
        /// <param name="nome">nome.</param>
        /// <param name="contaGrafica">contaGrafica.</param>
        /// <param name="dataConsulta">dataConsulta.</param>
        /// <param name="resumo">resumo.</param>
        /// <param name="ativos">ativos.</param>
        public CarteiraResponse(long clienteId = default(long), string nome = default(string), string contaGrafica = default(string), DateTime dataConsulta = default(DateTime), ResumoCarteira resumo = default(ResumoCarteira), List<AtivoCarteira> ativos = default(List<AtivoCarteira>))
        {
            this.ClienteId = clienteId;
            this.Nome = nome;
            this.ContaGrafica = contaGrafica;
            this.DataConsulta = dataConsulta;
            this.Resumo = resumo;
            this.Ativos = ativos;
        }

        /// <summary>
        /// Gets or Sets ClienteId
        /// </summary>
        [DataMember(Name = "clienteId", EmitDefaultValue = false)]
        public long ClienteId { get; set; }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", EmitDefaultValue = false)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets ContaGrafica
        /// </summary>
        [DataMember(Name = "contaGrafica", EmitDefaultValue = false)]
        public string ContaGrafica { get; set; }

        /// <summary>
        /// Gets or Sets DataConsulta
        /// </summary>
        [DataMember(Name = "dataConsulta", EmitDefaultValue = false)]
        public DateTime DataConsulta { get; set; }

        /// <summary>
        /// Gets or Sets Resumo
        /// </summary>
        [DataMember(Name = "resumo", EmitDefaultValue = false)]
        public ResumoCarteira Resumo { get; set; }

        /// <summary>
        /// Gets or Sets Ativos
        /// </summary>
        [DataMember(Name = "ativos", EmitDefaultValue = false)]
        public List<AtivoCarteira> Ativos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CarteiraResponse {\n");
            sb.Append("  ClienteId: ").Append(ClienteId).Append("\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  ContaGrafica: ").Append(ContaGrafica).Append("\n");
            sb.Append("  DataConsulta: ").Append(DataConsulta).Append("\n");
            sb.Append("  Resumo: ").Append(Resumo).Append("\n");
            sb.Append("  Ativos: ").Append(Ativos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
