/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CestaRequest
    /// </summary>
    [DataContract(Name = "CestaRequest")]
    public partial class CestaRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CestaRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CestaRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CestaRequest" /> class.
        /// </summary>
        /// <param name="nome">nome (required).</param>
        /// <param name="itens">itens (required).</param>
        public CestaRequest(string nome = default(string), List<ItemCesta> itens = default(List<ItemCesta>))
        {
            // to ensure "nome" is required (not null)
            if (nome == null)
            {
                throw new ArgumentNullException("nome is a required property for CestaRequest and cannot be null");
            }
            this.Nome = nome;
            // to ensure "itens" is required (not null)
            if (itens == null)
            {
                throw new ArgumentNullException("itens is a required property for CestaRequest and cannot be null");
            }
            this.Itens = itens;
        }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", IsRequired = true, EmitDefaultValue = true)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets Itens
        /// </summary>
        [DataMember(Name = "itens", IsRequired = true, EmitDefaultValue = true)]
        public List<ItemCesta> Itens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CestaRequest {\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  Itens: ").Append(Itens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
