/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CestaAtualResponse
    /// </summary>
    [DataContract(Name = "CestaAtualResponse")]
    public partial class CestaAtualResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CestaAtualResponse" /> class.
        /// </summary>
        /// <param name="cestaId">cestaId.</param>
        /// <param name="nome">nome.</param>
        /// <param name="ativa">ativa.</param>
        /// <param name="dataCriacao">dataCriacao.</param>
        /// <param name="itens">itens.</param>
        public CestaAtualResponse(long cestaId = default(long), string nome = default(string), bool ativa = default(bool), DateTime dataCriacao = default(DateTime), List<ItemCestaComCotacao> itens = default(List<ItemCestaComCotacao>))
        {
            this.CestaId = cestaId;
            this.Nome = nome;
            this.Ativa = ativa;
            this.DataCriacao = dataCriacao;
            this.Itens = itens;
        }

        /// <summary>
        /// Gets or Sets CestaId
        /// </summary>
        [DataMember(Name = "cestaId", EmitDefaultValue = false)]
        public long CestaId { get; set; }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", EmitDefaultValue = false)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets Ativa
        /// </summary>
        [DataMember(Name = "ativa", EmitDefaultValue = true)]
        public bool Ativa { get; set; }

        /// <summary>
        /// Gets or Sets DataCriacao
        /// </summary>
        [DataMember(Name = "dataCriacao", EmitDefaultValue = false)]
        public DateTime DataCriacao { get; set; }

        /// <summary>
        /// Gets or Sets Itens
        /// </summary>
        [DataMember(Name = "itens", EmitDefaultValue = false)]
        public List<ItemCestaComCotacao> Itens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CestaAtualResponse {\n");
            sb.Append("  CestaId: ").Append(CestaId).Append("\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  Ativa: ").Append(Ativa).Append("\n");
            sb.Append("  DataCriacao: ").Append(DataCriacao).Append("\n");
            sb.Append("  Itens: ").Append(Itens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
