/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CestaAnteriorDesativada
    /// </summary>
    [DataContract(Name = "CestaAnteriorDesativada")]
    public partial class CestaAnteriorDesativada : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CestaAnteriorDesativada" /> class.
        /// </summary>
        /// <param name="cestaId">cestaId.</param>
        /// <param name="nome">nome.</param>
        /// <param name="dataDesativacao">dataDesativacao.</param>
        public CestaAnteriorDesativada(long cestaId = default(long), string nome = default(string), DateTime dataDesativacao = default(DateTime))
        {
            this.CestaId = cestaId;
            this.Nome = nome;
            this.DataDesativacao = dataDesativacao;
        }

        /// <summary>
        /// Gets or Sets CestaId
        /// </summary>
        [DataMember(Name = "cestaId", EmitDefaultValue = false)]
        public long CestaId { get; set; }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", EmitDefaultValue = false)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets DataDesativacao
        /// </summary>
        [DataMember(Name = "dataDesativacao", EmitDefaultValue = false)]
        public DateTime DataDesativacao { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CestaAnteriorDesativada {\n");
            sb.Append("  CestaId: ").Append(CestaId).Append("\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  DataDesativacao: ").Append(DataDesativacao).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
