/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ContaMasterInfo
    /// </summary>
    [DataContract(Name = "ContaMasterInfo")]
    public partial class ContaMasterInfo : IValidatableObject
    {
        /// <summary>
        /// Defines Tipo
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TipoEnum
        {
            /// <summary>
            /// Enum MASTER for value: MASTER
            /// </summary>
            [EnumMember(Value = "MASTER")]
            MASTER = 1
        }


        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name = "tipo", EmitDefaultValue = false)]
        public TipoEnum? Tipo { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ContaMasterInfo" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="numeroConta">numeroConta.</param>
        /// <param name="tipo">tipo.</param>
        public ContaMasterInfo(long id = default(long), string numeroConta = default(string), TipoEnum? tipo = default(TipoEnum?))
        {
            this.Id = id;
            this.NumeroConta = numeroConta;
            this.Tipo = tipo;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public long Id { get; set; }

        /// <summary>
        /// Gets or Sets NumeroConta
        /// </summary>
        [DataMember(Name = "numeroConta", EmitDefaultValue = false)]
        public string NumeroConta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ContaMasterInfo {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  NumeroConta: ").Append(NumeroConta).Append("\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
