/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CustodiaMasterResponse
    /// </summary>
    [DataContract(Name = "CustodiaMasterResponse")]
    public partial class CustodiaMasterResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustodiaMasterResponse" /> class.
        /// </summary>
        /// <param name="contaMaster">contaMaster.</param>
        /// <param name="custodia">custodia.</param>
        /// <param name="valorTotalResiduo">valorTotalResiduo.</param>
        public CustodiaMasterResponse(ContaMasterInfo contaMaster = default(ContaMasterInfo), List<CustodiaMasterItem> custodia = default(List<CustodiaMasterItem>), double valorTotalResiduo = default(double))
        {
            this.ContaMaster = contaMaster;
            this.Custodia = custodia;
            this.ValorTotalResiduo = valorTotalResiduo;
        }

        /// <summary>
        /// Gets or Sets ContaMaster
        /// </summary>
        [DataMember(Name = "contaMaster", EmitDefaultValue = false)]
        public ContaMasterInfo ContaMaster { get; set; }

        /// <summary>
        /// Gets or Sets Custodia
        /// </summary>
        [DataMember(Name = "custodia", EmitDefaultValue = false)]
        public List<CustodiaMasterItem> Custodia { get; set; }

        /// <summary>
        /// Gets or Sets ValorTotalResiduo
        /// </summary>
        [DataMember(Name = "valorTotalResiduo", EmitDefaultValue = false)]
        public double ValorTotalResiduo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustodiaMasterResponse {\n");
            sb.Append("  ContaMaster: ").Append(ContaMaster).Append("\n");
            sb.Append("  Custodia: ").Append(Custodia).Append("\n");
            sb.Append("  ValorTotalResiduo: ").Append(ValorTotalResiduo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
