/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CustodiaMasterItem
    /// </summary>
    [DataContract(Name = "CustodiaMasterItem")]
    public partial class CustodiaMasterItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustodiaMasterItem" /> class.
        /// </summary>
        /// <param name="ticker">ticker.</param>
        /// <param name="quantidade">quantidade.</param>
        /// <param name="precoMedio">precoMedio.</param>
        /// <param name="valorAtual">valorAtual.</param>
        /// <param name="origem">origem.</param>
        public CustodiaMasterItem(string ticker = default(string), int quantidade = default(int), double precoMedio = default(double), double valorAtual = default(double), string origem = default(string))
        {
            this.Ticker = ticker;
            this.Quantidade = quantidade;
            this.PrecoMedio = precoMedio;
            this.ValorAtual = valorAtual;
            this.Origem = origem;
        }

        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name = "ticker", EmitDefaultValue = false)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets Quantidade
        /// </summary>
        [DataMember(Name = "quantidade", EmitDefaultValue = false)]
        public int Quantidade { get; set; }

        /// <summary>
        /// Gets or Sets PrecoMedio
        /// </summary>
        [DataMember(Name = "precoMedio", EmitDefaultValue = false)]
        public double PrecoMedio { get; set; }

        /// <summary>
        /// Gets or Sets ValorAtual
        /// </summary>
        [DataMember(Name = "valorAtual", EmitDefaultValue = false)]
        public double ValorAtual { get; set; }

        /// <summary>
        /// Gets or Sets Origem
        /// </summary>
        [DataMember(Name = "origem", EmitDefaultValue = false)]
        public string Origem { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CustodiaMasterItem {\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Quantidade: ").Append(Quantidade).Append("\n");
            sb.Append("  PrecoMedio: ").Append(PrecoMedio).Append("\n");
            sb.Append("  ValorAtual: ").Append(ValorAtual).Append("\n");
            sb.Append("  Origem: ").Append(Origem).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
