/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DetalheOrdemCompra
    /// </summary>
    [DataContract(Name = "DetalheOrdemCompra")]
    public partial class DetalheOrdemCompra : IValidatableObject
    {
        /// <summary>
        /// Defines Tipo
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TipoEnum
        {
            /// <summary>
            /// Enum FRACIONARIO for value: FRACIONARIO
            /// </summary>
            [EnumMember(Value = "FRACIONARIO")]
            FRACIONARIO = 1,

            /// <summary>
            /// Enum INTEIRO for value: INTEIRO
            /// </summary>
            [EnumMember(Value = "INTEIRO")]
            INTEIRO = 2
        }


        /// <summary>
        /// Gets or Sets Tipo
        /// </summary>
        [DataMember(Name = "tipo", EmitDefaultValue = false)]
        public TipoEnum? Tipo { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DetalheOrdemCompra" /> class.
        /// </summary>
        /// <param name="tipo">tipo.</param>
        /// <param name="ticker">ticker.</param>
        /// <param name="quantidade">quantidade.</param>
        public DetalheOrdemCompra(TipoEnum? tipo = default(TipoEnum?), string ticker = default(string), int quantidade = default(int))
        {
            this.Tipo = tipo;
            this.Ticker = ticker;
            this.Quantidade = quantidade;
        }

        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name = "ticker", EmitDefaultValue = false)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets Quantidade
        /// </summary>
        [DataMember(Name = "quantidade", EmitDefaultValue = false)]
        public int Quantidade { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DetalheOrdemCompra {\n");
            sb.Append("  Tipo: ").Append(Tipo).Append("\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Quantidade: ").Append(Quantidade).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
