/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DistribuicaoCliente
    /// </summary>
    [DataContract(Name = "DistribuicaoCliente")]
    public partial class DistribuicaoCliente : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DistribuicaoCliente" /> class.
        /// </summary>
        /// <param name="clienteId">clienteId.</param>
        /// <param name="nome">nome.</param>
        /// <param name="valorAporte">valorAporte.</param>
        /// <param name="ativos">ativos.</param>
        public DistribuicaoCliente(long clienteId = default(long), string nome = default(string), double valorAporte = default(double), List<AtivoDistribuido> ativos = default(List<AtivoDistribuido>))
        {
            this.ClienteId = clienteId;
            this.Nome = nome;
            this.ValorAporte = valorAporte;
            this.Ativos = ativos;
        }

        /// <summary>
        /// Gets or Sets ClienteId
        /// </summary>
        [DataMember(Name = "clienteId", EmitDefaultValue = false)]
        public long ClienteId { get; set; }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", EmitDefaultValue = false)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets ValorAporte
        /// </summary>
        [DataMember(Name = "valorAporte", EmitDefaultValue = false)]
        public double ValorAporte { get; set; }

        /// <summary>
        /// Gets or Sets Ativos
        /// </summary>
        [DataMember(Name = "ativos", EmitDefaultValue = false)]
        public List<AtivoDistribuido> Ativos { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DistribuicaoCliente {\n");
            sb.Append("  ClienteId: ").Append(ClienteId).Append("\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  ValorAporte: ").Append(ValorAporte).Append("\n");
            sb.Append("  Ativos: ").Append(Ativos).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
