/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ErrorResponse
    /// </summary>
    [DataContract(Name = "ErrorResponse")]
    public partial class ErrorResponse : IValidatableObject
    {
        /// <summary>
        /// Defines Codigo
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodigoEnum
        {
            /// <summary>
            /// Enum CLIENTECPFDUPLICADO for value: CLIENTE_CPF_DUPLICADO
            /// </summary>
            [EnumMember(Value = "CLIENTE_CPF_DUPLICADO")]
            CLIENTECPFDUPLICADO = 1,

            /// <summary>
            /// Enum VALORMENSALINVALIDO for value: VALOR_MENSAL_INVALIDO
            /// </summary>
            [EnumMember(Value = "VALOR_MENSAL_INVALIDO")]
            VALORMENSALINVALIDO = 2,

            /// <summary>
            /// Enum PERCENTUAISINVALIDOS for value: PERCENTUAIS_INVALIDOS
            /// </summary>
            [EnumMember(Value = "PERCENTUAIS_INVALIDOS")]
            PERCENTUAISINVALIDOS = 3,

            /// <summary>
            /// Enum QUANTIDADEATIVOSINVALIDA for value: QUANTIDADE_ATIVOS_INVALIDA
            /// </summary>
            [EnumMember(Value = "QUANTIDADE_ATIVOS_INVALIDA")]
            QUANTIDADEATIVOSINVALIDA = 4,

            /// <summary>
            /// Enum CLIENTEJAINATIVO for value: CLIENTE_JA_INATIVO
            /// </summary>
            [EnumMember(Value = "CLIENTE_JA_INATIVO")]
            CLIENTEJAINATIVO = 5,

            /// <summary>
            /// Enum CLIENTENAOENCONTRADO for value: CLIENTE_NAO_ENCONTRADO
            /// </summary>
            [EnumMember(Value = "CLIENTE_NAO_ENCONTRADO")]
            CLIENTENAOENCONTRADO = 6,

            /// <summary>
            /// Enum CESTANAOENCONTRADA for value: CESTA_NAO_ENCONTRADA
            /// </summary>
            [EnumMember(Value = "CESTA_NAO_ENCONTRADA")]
            CESTANAOENCONTRADA = 7,

            /// <summary>
            /// Enum COTACAONAOENCONTRADA for value: COTACAO_NAO_ENCONTRADA
            /// </summary>
            [EnumMember(Value = "COTACAO_NAO_ENCONTRADA")]
            COTACAONAOENCONTRADA = 8,

            /// <summary>
            /// Enum COMPRAJAEXECUTADA for value: COMPRA_JA_EXECUTADA
            /// </summary>
            [EnumMember(Value = "COMPRA_JA_EXECUTADA")]
            COMPRAJAEXECUTADA = 9,

            /// <summary>
            /// Enum KAFKAINDISPONIVEL for value: KAFKA_INDISPONIVEL
            /// </summary>
            [EnumMember(Value = "KAFKA_INDISPONIVEL")]
            KAFKAINDISPONIVEL = 10
        }


        /// <summary>
        /// Gets or Sets Codigo
        /// </summary>
        [DataMember(Name = "codigo", EmitDefaultValue = false)]
        public CodigoEnum? Codigo { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorResponse" /> class.
        /// </summary>
        /// <param name="erro">erro.</param>
        /// <param name="codigo">codigo.</param>
        public ErrorResponse(string erro = default(string), CodigoEnum? codigo = default(CodigoEnum?))
        {
            this.Erro = erro;
            this.Codigo = codigo;
        }

        /// <summary>
        /// Gets or Sets Erro
        /// </summary>
        [DataMember(Name = "erro", EmitDefaultValue = false)]
        public string Erro { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ErrorResponse {\n");
            sb.Append("  Erro: ").Append(Erro).Append("\n");
            sb.Append("  Codigo: ").Append(Codigo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
