/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// EvolucaoCarteira
    /// </summary>
    [DataContract(Name = "EvolucaoCarteira")]
    public partial class EvolucaoCarteira : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EvolucaoCarteira" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="valorCarteira">valorCarteira.</param>
        /// <param name="valorInvestido">valorInvestido.</param>
        /// <param name="rentabilidade">rentabilidade.</param>
        public EvolucaoCarteira(DateOnly data = default(DateOnly), double valorCarteira = default(double), double valorInvestido = default(double), double rentabilidade = default(double))
        {
            this.Data = data;
            this.ValorCarteira = valorCarteira;
            this.ValorInvestido = valorInvestido;
            this.Rentabilidade = rentabilidade;
        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public DateOnly Data { get; set; }

        /// <summary>
        /// Gets or Sets ValorCarteira
        /// </summary>
        [DataMember(Name = "valorCarteira", EmitDefaultValue = false)]
        public double ValorCarteira { get; set; }

        /// <summary>
        /// Gets or Sets ValorInvestido
        /// </summary>
        [DataMember(Name = "valorInvestido", EmitDefaultValue = false)]
        public double ValorInvestido { get; set; }

        /// <summary>
        /// Gets or Sets Rentabilidade
        /// </summary>
        [DataMember(Name = "rentabilidade", EmitDefaultValue = false)]
        public double Rentabilidade { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EvolucaoCarteira {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  ValorCarteira: ").Append(ValorCarteira).Append("\n");
            sb.Append("  ValorInvestido: ").Append(ValorInvestido).Append("\n");
            sb.Append("  Rentabilidade: ").Append(Rentabilidade).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
