/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ExecutarCompraResponse
    /// </summary>
    [DataContract(Name = "ExecutarCompraResponse")]
    public partial class ExecutarCompraResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExecutarCompraResponse" /> class.
        /// </summary>
        /// <param name="dataExecucao">dataExecucao.</param>
        /// <param name="totalClientes">totalClientes.</param>
        /// <param name="totalConsolidado">totalConsolidado.</param>
        /// <param name="ordensCompra">ordensCompra.</param>
        /// <param name="distribuicoes">distribuicoes.</param>
        /// <param name="residuosCustMaster">residuosCustMaster.</param>
        /// <param name="eventosIRPublicados">eventosIRPublicados.</param>
        /// <param name="mensagem">mensagem.</param>
        public ExecutarCompraResponse(DateTime dataExecucao = default(DateTime), int totalClientes = default(int), double totalConsolidado = default(double), List<OrdemCompra> ordensCompra = default(List<OrdemCompra>), List<DistribuicaoCliente> distribuicoes = default(List<DistribuicaoCliente>), List<ResiduoMaster> residuosCustMaster = default(List<ResiduoMaster>), int eventosIRPublicados = default(int), string mensagem = default(string))
        {
            this.DataExecucao = dataExecucao;
            this.TotalClientes = totalClientes;
            this.TotalConsolidado = totalConsolidado;
            this.OrdensCompra = ordensCompra;
            this.Distribuicoes = distribuicoes;
            this.ResiduosCustMaster = residuosCustMaster;
            this.EventosIRPublicados = eventosIRPublicados;
            this.Mensagem = mensagem;
        }

        /// <summary>
        /// Gets or Sets DataExecucao
        /// </summary>
        [DataMember(Name = "dataExecucao", EmitDefaultValue = false)]
        public DateTime DataExecucao { get; set; }

        /// <summary>
        /// Gets or Sets TotalClientes
        /// </summary>
        [DataMember(Name = "totalClientes", EmitDefaultValue = false)]
        public int TotalClientes { get; set; }

        /// <summary>
        /// Gets or Sets TotalConsolidado
        /// </summary>
        [DataMember(Name = "totalConsolidado", EmitDefaultValue = false)]
        public double TotalConsolidado { get; set; }

        /// <summary>
        /// Gets or Sets OrdensCompra
        /// </summary>
        [DataMember(Name = "ordensCompra", EmitDefaultValue = false)]
        public List<OrdemCompra> OrdensCompra { get; set; }

        /// <summary>
        /// Gets or Sets Distribuicoes
        /// </summary>
        [DataMember(Name = "distribuicoes", EmitDefaultValue = false)]
        public List<DistribuicaoCliente> Distribuicoes { get; set; }

        /// <summary>
        /// Gets or Sets ResiduosCustMaster
        /// </summary>
        [DataMember(Name = "residuosCustMaster", EmitDefaultValue = false)]
        public List<ResiduoMaster> ResiduosCustMaster { get; set; }

        /// <summary>
        /// Gets or Sets EventosIRPublicados
        /// </summary>
        [DataMember(Name = "eventosIRPublicados", EmitDefaultValue = false)]
        public int EventosIRPublicados { get; set; }

        /// <summary>
        /// Gets or Sets Mensagem
        /// </summary>
        [DataMember(Name = "mensagem", EmitDefaultValue = false)]
        public string Mensagem { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExecutarCompraResponse {\n");
            sb.Append("  DataExecucao: ").Append(DataExecucao).Append("\n");
            sb.Append("  TotalClientes: ").Append(TotalClientes).Append("\n");
            sb.Append("  TotalConsolidado: ").Append(TotalConsolidado).Append("\n");
            sb.Append("  OrdensCompra: ").Append(OrdensCompra).Append("\n");
            sb.Append("  Distribuicoes: ").Append(Distribuicoes).Append("\n");
            sb.Append("  ResiduosCustMaster: ").Append(ResiduosCustMaster).Append("\n");
            sb.Append("  EventosIRPublicados: ").Append(EventosIRPublicados).Append("\n");
            sb.Append("  Mensagem: ").Append(Mensagem).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
