/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// HistoricoAporte
    /// </summary>
    [DataContract(Name = "HistoricoAporte")]
    public partial class HistoricoAporte : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HistoricoAporte" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="valor">valor.</param>
        /// <param name="parcela">parcela.</param>
        public HistoricoAporte(DateOnly data = default(DateOnly), double valor = default(double), string parcela = default(string))
        {
            this.Data = data;
            this.Valor = valor;
            this.Parcela = parcela;
        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public DateOnly Data { get; set; }

        /// <summary>
        /// Gets or Sets Valor
        /// </summary>
        [DataMember(Name = "valor", EmitDefaultValue = false)]
        public double Valor { get; set; }

        /// <summary>
        /// Gets or Sets Parcela
        /// </summary>
        [DataMember(Name = "parcela", EmitDefaultValue = false)]
        public string Parcela { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class HistoricoAporte {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Valor: ").Append(Valor).Append("\n");
            sb.Append("  Parcela: ").Append(Parcela).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
