/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ItemCesta
    /// </summary>
    [DataContract(Name = "ItemCesta")]
    public partial class ItemCesta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemCesta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ItemCesta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemCesta" /> class.
        /// </summary>
        /// <param name="ticker">ticker (required).</param>
        /// <param name="percentual">percentual (required).</param>
        public ItemCesta(string ticker = default(string), double percentual = default(double))
        {
            // to ensure "ticker" is required (not null)
            if (ticker == null)
            {
                throw new ArgumentNullException("ticker is a required property for ItemCesta and cannot be null");
            }
            this.Ticker = ticker;
            this.Percentual = percentual;
        }

        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name = "ticker", IsRequired = true, EmitDefaultValue = true)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets Percentual
        /// </summary>
        [DataMember(Name = "percentual", IsRequired = true, EmitDefaultValue = true)]
        public double Percentual { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ItemCesta {\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Percentual: ").Append(Percentual).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Percentual (double) maximum
            if (this.Percentual > (double)100)
            {
                yield return new ValidationResult("Invalid value for Percentual, must be a value less than or equal to 100.", new [] { "Percentual" });
            }

            // Percentual (double) minimum
            if (this.Percentual < (double)0)
            {
                yield return new ValidationResult("Invalid value for Percentual, must be a value greater than or equal to 0.", new [] { "Percentual" });
            }

            yield break;
        }
    }

}
