/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ItemCestaComCotacao
    /// </summary>
    [DataContract(Name = "ItemCestaComCotacao")]
    public partial class ItemCestaComCotacao : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemCestaComCotacao" /> class.
        /// </summary>
        /// <param name="ticker">ticker.</param>
        /// <param name="percentual">percentual.</param>
        /// <param name="cotacaoAtual">cotacaoAtual.</param>
        public ItemCestaComCotacao(string ticker = default(string), double percentual = default(double), double cotacaoAtual = default(double))
        {
            this.Ticker = ticker;
            this.Percentual = percentual;
            this.CotacaoAtual = cotacaoAtual;
        }

        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name = "ticker", EmitDefaultValue = false)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets Percentual
        /// </summary>
        [DataMember(Name = "percentual", EmitDefaultValue = false)]
        public double Percentual { get; set; }

        /// <summary>
        /// Gets or Sets CotacaoAtual
        /// </summary>
        [DataMember(Name = "cotacaoAtual", EmitDefaultValue = false)]
        public double CotacaoAtual { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ItemCestaComCotacao {\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  Percentual: ").Append(Percentual).Append("\n");
            sb.Append("  CotacaoAtual: ").Append(CotacaoAtual).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
