/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OrdemCompra
    /// </summary>
    [DataContract(Name = "OrdemCompra")]
    public partial class OrdemCompra : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrdemCompra" /> class.
        /// </summary>
        /// <param name="ticker">ticker.</param>
        /// <param name="quantidadeTotal">quantidadeTotal.</param>
        /// <param name="detalhes">detalhes.</param>
        /// <param name="precoUnitario">precoUnitario.</param>
        /// <param name="valorTotal">valorTotal.</param>
        public OrdemCompra(string ticker = default(string), int quantidadeTotal = default(int), List<DetalheOrdemCompra> detalhes = default(List<DetalheOrdemCompra>), double precoUnitario = default(double), double valorTotal = default(double))
        {
            this.Ticker = ticker;
            this.QuantidadeTotal = quantidadeTotal;
            this.Detalhes = detalhes;
            this.PrecoUnitario = precoUnitario;
            this.ValorTotal = valorTotal;
        }

        /// <summary>
        /// Gets or Sets Ticker
        /// </summary>
        [DataMember(Name = "ticker", EmitDefaultValue = false)]
        public string Ticker { get; set; }

        /// <summary>
        /// Gets or Sets QuantidadeTotal
        /// </summary>
        [DataMember(Name = "quantidadeTotal", EmitDefaultValue = false)]
        public int QuantidadeTotal { get; set; }

        /// <summary>
        /// Gets or Sets Detalhes
        /// </summary>
        [DataMember(Name = "detalhes", EmitDefaultValue = false)]
        public List<DetalheOrdemCompra> Detalhes { get; set; }

        /// <summary>
        /// Gets or Sets PrecoUnitario
        /// </summary>
        [DataMember(Name = "precoUnitario", EmitDefaultValue = false)]
        public double PrecoUnitario { get; set; }

        /// <summary>
        /// Gets or Sets ValorTotal
        /// </summary>
        [DataMember(Name = "valorTotal", EmitDefaultValue = false)]
        public double ValorTotal { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrdemCompra {\n");
            sb.Append("  Ticker: ").Append(Ticker).Append("\n");
            sb.Append("  QuantidadeTotal: ").Append(QuantidadeTotal).Append("\n");
            sb.Append("  Detalhes: ").Append(Detalhes).Append("\n");
            sb.Append("  PrecoUnitario: ").Append(PrecoUnitario).Append("\n");
            sb.Append("  ValorTotal: ").Append(ValorTotal).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
