/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// RentabilidadeResponse
    /// </summary>
    [DataContract(Name = "RentabilidadeResponse")]
    public partial class RentabilidadeResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RentabilidadeResponse" /> class.
        /// </summary>
        /// <param name="clienteId">clienteId.</param>
        /// <param name="nome">nome.</param>
        /// <param name="dataConsulta">dataConsulta.</param>
        /// <param name="rentabilidade">rentabilidade.</param>
        /// <param name="historicoAportes">historicoAportes.</param>
        /// <param name="evolucaoCarteira">evolucaoCarteira.</param>
        public RentabilidadeResponse(long clienteId = default(long), string nome = default(string), DateTime dataConsulta = default(DateTime), ResumoCarteira rentabilidade = default(ResumoCarteira), List<HistoricoAporte> historicoAportes = default(List<HistoricoAporte>), List<EvolucaoCarteira> evolucaoCarteira = default(List<EvolucaoCarteira>))
        {
            this.ClienteId = clienteId;
            this.Nome = nome;
            this.DataConsulta = dataConsulta;
            this.Rentabilidade = rentabilidade;
            this.HistoricoAportes = historicoAportes;
            this.EvolucaoCarteira = evolucaoCarteira;
        }

        /// <summary>
        /// Gets or Sets ClienteId
        /// </summary>
        [DataMember(Name = "clienteId", EmitDefaultValue = false)]
        public long ClienteId { get; set; }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", EmitDefaultValue = false)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets DataConsulta
        /// </summary>
        [DataMember(Name = "dataConsulta", EmitDefaultValue = false)]
        public DateTime DataConsulta { get; set; }

        /// <summary>
        /// Gets or Sets Rentabilidade
        /// </summary>
        [DataMember(Name = "rentabilidade", EmitDefaultValue = false)]
        public ResumoCarteira Rentabilidade { get; set; }

        /// <summary>
        /// Gets or Sets HistoricoAportes
        /// </summary>
        [DataMember(Name = "historicoAportes", EmitDefaultValue = false)]
        public List<HistoricoAporte> HistoricoAportes { get; set; }

        /// <summary>
        /// Gets or Sets EvolucaoCarteira
        /// </summary>
        [DataMember(Name = "evolucaoCarteira", EmitDefaultValue = false)]
        public List<EvolucaoCarteira> EvolucaoCarteira { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RentabilidadeResponse {\n");
            sb.Append("  ClienteId: ").Append(ClienteId).Append("\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  DataConsulta: ").Append(DataConsulta).Append("\n");
            sb.Append("  Rentabilidade: ").Append(Rentabilidade).Append("\n");
            sb.Append("  HistoricoAportes: ").Append(HistoricoAportes).Append("\n");
            sb.Append("  EvolucaoCarteira: ").Append(EvolucaoCarteira).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
