/*
 * Sistema de Compra Programada de Ações - Itaú Corretora
 *
 * API REST para o sistema de compra programada de ações
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ResumoCarteira
    /// </summary>
    [DataContract(Name = "ResumoCarteira")]
    public partial class ResumoCarteira : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResumoCarteira" /> class.
        /// </summary>
        /// <param name="valorTotalInvestido">valorTotalInvestido.</param>
        /// <param name="valorAtualCarteira">valorAtualCarteira.</param>
        /// <param name="plTotal">plTotal.</param>
        /// <param name="rentabilidadePercentual">rentabilidadePercentual.</param>
        public ResumoCarteira(double valorTotalInvestido = default(double), double valorAtualCarteira = default(double), double plTotal = default(double), double rentabilidadePercentual = default(double))
        {
            this.ValorTotalInvestido = valorTotalInvestido;
            this.ValorAtualCarteira = valorAtualCarteira;
            this.PlTotal = plTotal;
            this.RentabilidadePercentual = rentabilidadePercentual;
        }

        /// <summary>
        /// Gets or Sets ValorTotalInvestido
        /// </summary>
        [DataMember(Name = "valorTotalInvestido", EmitDefaultValue = false)]
        public double ValorTotalInvestido { get; set; }

        /// <summary>
        /// Gets or Sets ValorAtualCarteira
        /// </summary>
        [DataMember(Name = "valorAtualCarteira", EmitDefaultValue = false)]
        public double ValorAtualCarteira { get; set; }

        /// <summary>
        /// Gets or Sets PlTotal
        /// </summary>
        [DataMember(Name = "plTotal", EmitDefaultValue = false)]
        public double PlTotal { get; set; }

        /// <summary>
        /// Gets or Sets RentabilidadePercentual
        /// </summary>
        [DataMember(Name = "rentabilidadePercentual", EmitDefaultValue = false)]
        public double RentabilidadePercentual { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResumoCarteira {\n");
            sb.Append("  ValorTotalInvestido: ").Append(ValorTotalInvestido).Append("\n");
            sb.Append("  ValorAtualCarteira: ").Append(ValorAtualCarteira).Append("\n");
            sb.Append("  PlTotal: ").Append(PlTotal).Append("\n");
            sb.Append("  RentabilidadePercentual: ").Append(RentabilidadePercentual).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
